# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_demo_1.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1590, 811)
        self.formGroupBox = QtWidgets.QGroupBox(Form)
        self.formGroupBox.setGeometry(QtCore.QRect(20, 20, 167, 301))
        self.formGroupBox.setObjectName("formGroupBox")
        self.formLayout = QtWidgets.QFormLayout(self.formGroupBox)
        self.formLayout.setContentsMargins(10, 10, 10, 10)
        self.formLayout.setSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.s1__lb_1 = QtWidgets.QLabel(self.formGroupBox)
        self.s1__lb_1.setObjectName("s1__lb_1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.s1__lb_1)
        self.s1__box_1 = QtWidgets.QPushButton(self.formGroupBox)
        self.s1__box_1.setAutoRepeatInterval(100)
        self.s1__box_1.setDefault(True)
        self.s1__box_1.setObjectName("s1__box_1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.s1__box_1)
        self.s1__lb_2 = QtWidgets.QLabel(self.formGroupBox)
        self.s1__lb_2.setObjectName("s1__lb_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.s1__lb_2)
        self.s1__box_2 = QtWidgets.QComboBox(self.formGroupBox)
        self.s1__box_2.setObjectName("s1__box_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.s1__box_2)
        self.s1__lb_3 = QtWidgets.QLabel(self.formGroupBox)
        self.s1__lb_3.setObjectName("s1__lb_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.s1__lb_3)
        self.s1__box_3 = QtWidgets.QComboBox(self.formGroupBox)
        self.s1__box_3.setObjectName("s1__box_3")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.s1__box_3)
        self.s1__lb_4 = QtWidgets.QLabel(self.formGroupBox)
        self.s1__lb_4.setObjectName("s1__lb_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.s1__lb_4)
        self.s1__box_4 = QtWidgets.QComboBox(self.formGroupBox)
        self.s1__box_4.setObjectName("s1__box_4")
        self.s1__box_4.addItem("")
        self.s1__box_4.addItem("")
        self.s1__box_4.addItem("")
        self.s1__box_4.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.s1__box_4)
        self.s1__lb_5 = QtWidgets.QLabel(self.formGroupBox)
        self.s1__lb_5.setObjectName("s1__lb_5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.s1__lb_5)
        self.s1__box_5 = QtWidgets.QComboBox(self.formGroupBox)
        self.s1__box_5.setObjectName("s1__box_5")
        self.s1__box_5.addItem("")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.s1__box_5)
        self.open_button = QtWidgets.QPushButton(self.formGroupBox)
        self.open_button.setObjectName("open_button")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.open_button)
        self.close_button = QtWidgets.QPushButton(self.formGroupBox)
        self.close_button.setObjectName("close_button")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.SpanningRole, self.close_button)
        self.s1__lb_6 = QtWidgets.QLabel(self.formGroupBox)
        self.s1__lb_6.setObjectName("s1__lb_6")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.s1__lb_6)
        self.s1__box_6 = QtWidgets.QComboBox(self.formGroupBox)
        self.s1__box_6.setObjectName("s1__box_6")
        self.s1__box_6.addItem("")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.s1__box_6)
        self.state_label = QtWidgets.QLabel(self.formGroupBox)
        self.state_label.setText("")
        self.state_label.setTextFormat(QtCore.Qt.AutoText)
        self.state_label.setScaledContents(True)
        self.state_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.state_label.setObjectName("state_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.state_label)
        self.formGroupBox1 = QtWidgets.QGroupBox(Form)
        self.formGroupBox1.setGeometry(QtCore.QRect(20, 340, 171, 101))
        self.formGroupBox1.setObjectName("formGroupBox1")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formGroupBox1)
        self.formLayout_2.setContentsMargins(10, 10, 10, 10)
        self.formLayout_2.setSpacing(10)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.formGroupBox1)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.formGroupBox1)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.formGroupBox1)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.formGroupBox1)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(210, 20, 361, 671))
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 30, 240, 23))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.s1__lb_22 = QtWidgets.QLabel(self.layoutWidget)
        self.s1__lb_22.setObjectName("s1__lb_22")
        self.horizontalLayout.addWidget(self.s1__lb_22)
        self.Identity = QtWidgets.QLineEdit(self.layoutWidget)
        self.Identity.setObjectName("Identity")
        self.horizontalLayout.addWidget(self.Identity)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 70, 225, 23))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.s1__lb_23 = QtWidgets.QLabel(self.layoutWidget1)
        self.s1__lb_23.setObjectName("s1__lb_23")
        self.horizontalLayout_2.addWidget(self.s1__lb_23)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_2.addWidget(self.lineEdit_7)
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget2.setGeometry(QtCore.QRect(30, 110, 261, 31))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.s1__lb_20 = QtWidgets.QLabel(self.layoutWidget2)
        self.s1__lb_20.setObjectName("s1__lb_20")
        self.horizontalLayout_3.addWidget(self.s1__lb_20)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_3.addWidget(self.lineEdit_6)
        self.dw_10 = QtWidgets.QLabel(self.layoutWidget2)
        self.dw_10.setObjectName("dw_10")
        self.horizontalLayout_3.addWidget(self.dw_10)
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget3.setGeometry(QtCore.QRect(30, 150, 261, 23))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.s1__lb_21 = QtWidgets.QLabel(self.layoutWidget3)
        self.s1__lb_21.setObjectName("s1__lb_21")
        self.horizontalLayout_4.addWidget(self.s1__lb_21)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_4.addWidget(self.lineEdit_4)
        self.dw_11 = QtWidgets.QLabel(self.layoutWidget3)
        self.dw_11.setObjectName("dw_11")
        self.horizontalLayout_4.addWidget(self.dw_11)
        self.layoutWidget4 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget4.setGeometry(QtCore.QRect(30, 190, 271, 23))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.s1__lb_24 = QtWidgets.QLabel(self.layoutWidget4)
        self.s1__lb_24.setObjectName("s1__lb_24")
        self.horizontalLayout_5.addWidget(self.s1__lb_24)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.horizontalLayout_5.addWidget(self.lineEdit_8)
        self.dw_12 = QtWidgets.QLabel(self.layoutWidget4)
        self.dw_12.setObjectName("dw_12")
        self.horizontalLayout_5.addWidget(self.dw_12)
        self.layoutWidget5 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget5.setGeometry(QtCore.QRect(30, 230, 271, 23))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.s1__lb_25 = QtWidgets.QLabel(self.layoutWidget5)
        self.s1__lb_25.setObjectName("s1__lb_25")
        self.horizontalLayout_6.addWidget(self.s1__lb_25)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.layoutWidget5)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.horizontalLayout_6.addWidget(self.lineEdit_9)
        self.dw_13 = QtWidgets.QLabel(self.layoutWidget5)
        self.dw_13.setObjectName("dw_13")
        self.horizontalLayout_6.addWidget(self.dw_13)
        self.layoutWidget6 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget6.setGeometry(QtCore.QRect(30, 270, 271, 23))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.s1__lb_26 = QtWidgets.QLabel(self.layoutWidget6)
        self.s1__lb_26.setObjectName("s1__lb_26")
        self.horizontalLayout_7.addWidget(self.s1__lb_26)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.layoutWidget6)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.horizontalLayout_7.addWidget(self.lineEdit_10)
        self.dw_14 = QtWidgets.QLabel(self.layoutWidget6)
        self.dw_14.setObjectName("dw_14")
        self.horizontalLayout_7.addWidget(self.dw_14)
        self.layoutWidget7 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget7.setGeometry(QtCore.QRect(30, 310, 271, 23))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget7)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.s1__lb_27 = QtWidgets.QLabel(self.layoutWidget7)
        self.s1__lb_27.setObjectName("s1__lb_27")
        self.horizontalLayout_8.addWidget(self.s1__lb_27)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.layoutWidget7)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.horizontalLayout_8.addWidget(self.lineEdit_11)
        self.dw_15 = QtWidgets.QLabel(self.layoutWidget7)
        self.dw_15.setObjectName("dw_15")
        self.horizontalLayout_8.addWidget(self.dw_15)
        self.layoutWidget8 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget8.setGeometry(QtCore.QRect(30, 350, 271, 23))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.layoutWidget8)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.s1__lb_28 = QtWidgets.QLabel(self.layoutWidget8)
        self.s1__lb_28.setObjectName("s1__lb_28")
        self.horizontalLayout_9.addWidget(self.s1__lb_28)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.layoutWidget8)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.horizontalLayout_9.addWidget(self.lineEdit_12)
        self.dw_16 = QtWidgets.QLabel(self.layoutWidget8)
        self.dw_16.setObjectName("dw_16")
        self.horizontalLayout_9.addWidget(self.dw_16)
        self.layoutWidget9 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget9.setGeometry(QtCore.QRect(30, 390, 271, 23))
        self.layoutWidget9.setObjectName("layoutWidget9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.layoutWidget9)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.s1__lb_29 = QtWidgets.QLabel(self.layoutWidget9)
        self.s1__lb_29.setObjectName("s1__lb_29")
        self.horizontalLayout_10.addWidget(self.s1__lb_29)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.layoutWidget9)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.horizontalLayout_10.addWidget(self.lineEdit_13)
        self.dw_17 = QtWidgets.QLabel(self.layoutWidget9)
        self.dw_17.setObjectName("dw_17")
        self.horizontalLayout_10.addWidget(self.dw_17)
        self.layoutWidget10 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget10.setGeometry(QtCore.QRect(30, 430, 311, 23))
        self.layoutWidget10.setObjectName("layoutWidget10")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.layoutWidget10)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.s1__lb_30 = QtWidgets.QLabel(self.layoutWidget10)
        self.s1__lb_30.setObjectName("s1__lb_30")
        self.horizontalLayout_11.addWidget(self.s1__lb_30)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.layoutWidget10)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.horizontalLayout_11.addWidget(self.lineEdit_14)
        self.dw_18 = QtWidgets.QLabel(self.layoutWidget10)
        self.dw_18.setObjectName("dw_18")
        self.horizontalLayout_11.addWidget(self.dw_18)
        self.layoutWidget11 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget11.setGeometry(QtCore.QRect(30, 470, 311, 23))
        self.layoutWidget11.setObjectName("layoutWidget11")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.layoutWidget11)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.s1__lb_31 = QtWidgets.QLabel(self.layoutWidget11)
        self.s1__lb_31.setObjectName("s1__lb_31")
        self.horizontalLayout_12.addWidget(self.s1__lb_31)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.layoutWidget11)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.horizontalLayout_12.addWidget(self.lineEdit_15)
        self.dw_19 = QtWidgets.QLabel(self.layoutWidget11)
        self.dw_19.setObjectName("dw_19")
        self.horizontalLayout_12.addWidget(self.dw_19)
        self.layoutWidget12 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget12.setGeometry(QtCore.QRect(30, 510, 285, 23))
        self.layoutWidget12.setObjectName("layoutWidget12")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.layoutWidget12)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.s1__lb_32 = QtWidgets.QLabel(self.layoutWidget12)
        self.s1__lb_32.setObjectName("s1__lb_32")
        self.horizontalLayout_13.addWidget(self.s1__lb_32)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.layoutWidget12)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.horizontalLayout_13.addWidget(self.lineEdit_16)
        self.dw_20 = QtWidgets.QLabel(self.layoutWidget12)
        self.dw_20.setObjectName("dw_20")
        self.horizontalLayout_13.addWidget(self.dw_20)
        self.layoutWidget13 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget13.setGeometry(QtCore.QRect(30, 550, 293, 23))
        self.layoutWidget13.setObjectName("layoutWidget13")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.layoutWidget13)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.s1__lb_33 = QtWidgets.QLabel(self.layoutWidget13)
        self.s1__lb_33.setObjectName("s1__lb_33")
        self.horizontalLayout_14.addWidget(self.s1__lb_33)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.layoutWidget13)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.horizontalLayout_14.addWidget(self.lineEdit_17)
        self.dw_21 = QtWidgets.QLabel(self.layoutWidget13)
        self.dw_21.setObjectName("dw_21")
        self.horizontalLayout_14.addWidget(self.dw_21)
        self.layoutWidget14 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget14.setGeometry(QtCore.QRect(30, 590, 291, 23))
        self.layoutWidget14.setObjectName("layoutWidget14")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.layoutWidget14)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.s1__lb_34 = QtWidgets.QLabel(self.layoutWidget14)
        self.s1__lb_34.setObjectName("s1__lb_34")
        self.horizontalLayout_15.addWidget(self.s1__lb_34)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.layoutWidget14)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.horizontalLayout_15.addWidget(self.lineEdit_18)
        self.dw_22 = QtWidgets.QLabel(self.layoutWidget14)
        self.dw_22.setObjectName("dw_22")
        self.horizontalLayout_15.addWidget(self.dw_22)
        self.layoutWidget15 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget15.setGeometry(QtCore.QRect(30, 630, 285, 23))
        self.layoutWidget15.setObjectName("layoutWidget15")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.layoutWidget15)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.s1__lb_35 = QtWidgets.QLabel(self.layoutWidget15)
        self.s1__lb_35.setObjectName("s1__lb_35")
        self.horizontalLayout_16.addWidget(self.s1__lb_35)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.layoutWidget15)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.horizontalLayout_16.addWidget(self.lineEdit_19)
        self.dw_23 = QtWidgets.QLabel(self.layoutWidget15)
        self.dw_23.setObjectName("dw_23")
        self.horizontalLayout_16.addWidget(self.dw_23)
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 460, 171, 281))
        self.groupBox_3.setObjectName("groupBox_3")
        self.s3__send_button_3 = QtWidgets.QPushButton(self.groupBox_3)
        self.s3__send_button_3.setGeometry(QtCore.QRect(30, 40, 111, 31))
        self.s3__send_button_3.setObjectName("s3__send_button_3")
        self.send_SET = QtWidgets.QPushButton(self.groupBox_3)
        self.send_SET.setGeometry(QtCore.QRect(30, 130, 111, 31))
        self.send_SET.setObjectName("send_SET")
        self.polling = QtWidgets.QCheckBox(self.groupBox_3)
        self.polling.setGeometry(QtCore.QRect(40, 80, 71, 16))
        self.polling.setObjectName("polling")
        self.pollingtime = QtWidgets.QLineEdit(self.groupBox_3)
        self.pollingtime.setGeometry(QtCore.QRect(40, 100, 61, 21))
        self.pollingtime.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pollingtime.setObjectName("pollingtime")
        self.dw_2 = QtWidgets.QLabel(self.groupBox_3)
        self.dw_2.setGeometry(QtCore.QRect(110, 100, 54, 20))
        self.dw_2.setObjectName("dw_2")
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setGeometry(QtCore.QRect(590, 20, 991, 761))
        self.groupBox_4.setObjectName("groupBox_4")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_5.setGeometry(QtCore.QRect(20, 20, 311, 141))
        self.groupBox_5.setObjectName("groupBox_5")
        self.s1__lb_38 = QtWidgets.QLabel(self.groupBox_5)
        self.s1__lb_38.setGeometry(QtCore.QRect(20, 100, 108, 29))
        self.s1__lb_38.setObjectName("s1__lb_38")
        self.s1__lb_36 = QtWidgets.QLabel(self.groupBox_5)
        self.s1__lb_36.setGeometry(QtCore.QRect(20, 20, 108, 29))
        self.s1__lb_36.setObjectName("s1__lb_36")
        self.faultType = QtWidgets.QTextBrowser(self.groupBox_5)
        self.faultType.setGeometry(QtCore.QRect(140, 60, 141, 31))
        self.faultType.setObjectName("faultType")
        self.runState = QtWidgets.QTextBrowser(self.groupBox_5)
        self.runState.setGeometry(QtCore.QRect(140, 20, 141, 31))
        self.runState.setObjectName("runState")
        self.faultInfo = QtWidgets.QTextBrowser(self.groupBox_5)
        self.faultInfo.setGeometry(QtCore.QRect(140, 100, 141, 31))
        self.faultInfo.setObjectName("faultInfo")
        self.s1__lb_37 = QtWidgets.QLabel(self.groupBox_5)
        self.s1__lb_37.setGeometry(QtCore.QRect(20, 60, 108, 29))
        self.s1__lb_37.setObjectName("s1__lb_37")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_6.setGeometry(QtCore.QRect(20, 180, 311, 241))
        self.groupBox_6.setObjectName("groupBox_6")
        self.min_volt = QtWidgets.QTextBrowser(self.groupBox_6)
        self.min_volt.setGeometry(QtCore.QRect(150, 190, 121, 31))
        self.min_volt.setObjectName("min_volt")
        self.dw_25 = QtWidgets.QLabel(self.groupBox_6)
        self.dw_25.setGeometry(QtCore.QRect(280, 110, 41, 29))
        self.dw_25.setObjectName("dw_25")
        self.s1__lb_42 = QtWidgets.QLabel(self.groupBox_6)
        self.s1__lb_42.setGeometry(QtCore.QRect(10, 150, 141, 29))
        self.s1__lb_42.setObjectName("s1__lb_42")
        self.dw_24 = QtWidgets.QLabel(self.groupBox_6)
        self.dw_24.setGeometry(QtCore.QRect(280, 70, 41, 29))
        self.dw_24.setObjectName("dw_24")
        self.motorspd_12 = QtWidgets.QTextBrowser(self.groupBox_6)
        self.motorspd_12.setGeometry(QtCore.QRect(130, 30, 141, 31))
        self.motorspd_12.setObjectName("motorspd_12")
        self.max_temper = QtWidgets.QTextBrowser(self.groupBox_6)
        self.max_temper.setGeometry(QtCore.QRect(130, 150, 141, 31))
        self.max_temper.setObjectName("max_temper")
        self.s1__lb_43 = QtWidgets.QLabel(self.groupBox_6)
        self.s1__lb_43.setGeometry(QtCore.QRect(10, 190, 141, 29))
        self.s1__lb_43.setObjectName("s1__lb_43")
        self.max_volt = QtWidgets.QTextBrowser(self.groupBox_6)
        self.max_volt.setGeometry(QtCore.QRect(150, 110, 121, 31))
        self.max_volt.setObjectName("max_volt")
        self.max_cur = QtWidgets.QTextBrowser(self.groupBox_6)
        self.max_cur.setGeometry(QtCore.QRect(130, 70, 141, 31))
        self.max_cur.setObjectName("max_cur")
        self.s1__lb_39 = QtWidgets.QLabel(self.groupBox_6)
        self.s1__lb_39.setGeometry(QtCore.QRect(10, 30, 108, 29))
        self.s1__lb_39.setObjectName("s1__lb_39")
        self.s1__lb_40 = QtWidgets.QLabel(self.groupBox_6)
        self.s1__lb_40.setGeometry(QtCore.QRect(10, 70, 121, 29))
        self.s1__lb_40.setObjectName("s1__lb_40")
        self.dw_27 = QtWidgets.QLabel(self.groupBox_6)
        self.dw_27.setGeometry(QtCore.QRect(280, 190, 41, 29))
        self.dw_27.setObjectName("dw_27")
        self.s1__lb_41 = QtWidgets.QLabel(self.groupBox_6)
        self.s1__lb_41.setGeometry(QtCore.QRect(10, 110, 141, 29))
        self.s1__lb_41.setObjectName("s1__lb_41")
        self.dw_26 = QtWidgets.QLabel(self.groupBox_6)
        self.dw_26.setGeometry(QtCore.QRect(280, 150, 41, 29))
        self.dw_26.setObjectName("dw_26")
        self.outCur = QtWidgets.QGroupBox(self.groupBox_4)
        self.outCur.setGeometry(QtCore.QRect(340, 20, 301, 361))
        self.outCur.setObjectName("outCur")
        self.s1__lb_44 = QtWidgets.QLabel(self.outCur)
        self.s1__lb_44.setGeometry(QtCore.QRect(20, 20, 108, 29))
        self.s1__lb_44.setObjectName("s1__lb_44")
        self.setFreq = QtWidgets.QTextBrowser(self.outCur)
        self.setFreq.setGeometry(QtCore.QRect(100, 20, 141, 31))
        self.setFreq.setObjectName("setFreq")
        self.dw_28 = QtWidgets.QLabel(self.outCur)
        self.dw_28.setGeometry(QtCore.QRect(250, 20, 41, 29))
        self.dw_28.setObjectName("dw_28")
        self.s1__lb_45 = QtWidgets.QLabel(self.outCur)
        self.s1__lb_45.setGeometry(QtCore.QRect(20, 60, 108, 29))
        self.s1__lb_45.setObjectName("s1__lb_45")
        self.outFreq = QtWidgets.QTextBrowser(self.outCur)
        self.outFreq.setGeometry(QtCore.QRect(100, 60, 141, 31))
        self.outFreq.setObjectName("outFreq")
        self.dw_29 = QtWidgets.QLabel(self.outCur)
        self.dw_29.setGeometry(QtCore.QRect(250, 60, 41, 29))
        self.dw_29.setObjectName("dw_29")
        self.s1__lb_46 = QtWidgets.QLabel(self.outCur)
        self.s1__lb_46.setGeometry(QtCore.QRect(20, 100, 108, 29))
        self.s1__lb_46.setObjectName("s1__lb_46")
        self.outCur_2 = QtWidgets.QTextBrowser(self.outCur)
        self.outCur_2.setGeometry(QtCore.QRect(100, 100, 141, 31))
        self.outCur_2.setObjectName("outCur_2")
        self.dw_30 = QtWidgets.QLabel(self.outCur)
        self.dw_30.setGeometry(QtCore.QRect(250, 100, 41, 29))
        self.dw_30.setObjectName("dw_30")
        self.s1__lb_47 = QtWidgets.QLabel(self.outCur)
        self.s1__lb_47.setGeometry(QtCore.QRect(20, 140, 108, 29))
        self.s1__lb_47.setObjectName("s1__lb_47")
        self.inVolt = QtWidgets.QTextBrowser(self.outCur)
        self.inVolt.setGeometry(QtCore.QRect(100, 140, 141, 31))
        self.inVolt.setObjectName("inVolt")
        self.dw_31 = QtWidgets.QLabel(self.outCur)
        self.dw_31.setGeometry(QtCore.QRect(250, 140, 41, 29))
        self.dw_31.setObjectName("dw_31")
        self.s1__lb_48 = QtWidgets.QLabel(self.outCur)
        self.s1__lb_48.setGeometry(QtCore.QRect(20, 180, 108, 29))
        self.s1__lb_48.setObjectName("s1__lb_48")
        self.dw_32 = QtWidgets.QLabel(self.outCur)
        self.dw_32.setGeometry(QtCore.QRect(250, 180, 41, 29))
        self.dw_32.setObjectName("dw_32")
        self.outVolt = QtWidgets.QTextBrowser(self.outCur)
        self.outVolt.setGeometry(QtCore.QRect(100, 180, 141, 31))
        self.outVolt.setObjectName("outVolt")
        self.s1__lb_49 = QtWidgets.QLabel(self.outCur)
        self.s1__lb_49.setGeometry(QtCore.QRect(20, 220, 108, 29))
        self.s1__lb_49.setObjectName("s1__lb_49")
        self.motorspd_t = QtWidgets.QTextBrowser(self.outCur)
        self.motorspd_t.setGeometry(QtCore.QRect(100, 220, 141, 31))
        self.motorspd_t.setObjectName("motorspd_t")
        self.dw_33 = QtWidgets.QLabel(self.outCur)
        self.dw_33.setGeometry(QtCore.QRect(250, 220, 41, 29))
        self.dw_33.setObjectName("dw_33")
        self.s1__lb_50 = QtWidgets.QLabel(self.outCur)
        self.s1__lb_50.setGeometry(QtCore.QRect(20, 260, 108, 29))
        self.s1__lb_50.setObjectName("s1__lb_50")
        self.busVolt = QtWidgets.QTextBrowser(self.outCur)
        self.busVolt.setGeometry(QtCore.QRect(100, 260, 141, 31))
        self.busVolt.setObjectName("busVolt")
        self.dw_34 = QtWidgets.QLabel(self.outCur)
        self.dw_34.setGeometry(QtCore.QRect(250, 260, 41, 29))
        self.dw_34.setObjectName("dw_34")
        self.s1__lb_51 = QtWidgets.QLabel(self.outCur)
        self.s1__lb_51.setGeometry(QtCore.QRect(20, 300, 108, 29))
        self.s1__lb_51.setObjectName("s1__lb_51")
        self.outPower = QtWidgets.QTextBrowser(self.outCur)
        self.outPower.setGeometry(QtCore.QRect(100, 300, 141, 31))
        self.outPower.setObjectName("outPower")
        self.dw_35 = QtWidgets.QLabel(self.outCur)
        self.dw_35.setGeometry(QtCore.QRect(250, 300, 41, 29))
        self.dw_35.setObjectName("dw_35")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox.setGeometry(QtCore.QRect(20, 430, 311, 261))
        self.groupBox.setObjectName("groupBox")
        self.dw_36 = QtWidgets.QLabel(self.groupBox)
        self.dw_36.setGeometry(QtCore.QRect(200, 20, 41, 29))
        self.dw_36.setObjectName("dw_36")
        self.temper1 = QtWidgets.QTextBrowser(self.groupBox)
        self.temper1.setGeometry(QtCore.QRect(90, 20, 101, 31))
        self.temper1.setObjectName("temper1")
        self.s1__lb_52 = QtWidgets.QLabel(self.groupBox)
        self.s1__lb_52.setGeometry(QtCore.QRect(10, 20, 108, 29))
        self.s1__lb_52.setObjectName("s1__lb_52")
        self.dw_37 = QtWidgets.QLabel(self.groupBox)
        self.dw_37.setGeometry(QtCore.QRect(200, 60, 41, 29))
        self.dw_37.setObjectName("dw_37")
        self.temper2 = QtWidgets.QTextBrowser(self.groupBox)
        self.temper2.setGeometry(QtCore.QRect(90, 60, 101, 31))
        self.temper2.setObjectName("temper2")
        self.s1__lb_53 = QtWidgets.QLabel(self.groupBox)
        self.s1__lb_53.setGeometry(QtCore.QRect(10, 60, 108, 29))
        self.s1__lb_53.setObjectName("s1__lb_53")
        self.s1__lb_54 = QtWidgets.QLabel(self.groupBox)
        self.s1__lb_54.setGeometry(QtCore.QRect(10, 100, 108, 29))
        self.s1__lb_54.setObjectName("s1__lb_54")
        self.setTor = QtWidgets.QTextBrowser(self.groupBox)
        self.setTor.setGeometry(QtCore.QRect(90, 100, 101, 31))
        self.setTor.setObjectName("setTor")
        self.dw_38 = QtWidgets.QLabel(self.groupBox)
        self.dw_38.setGeometry(QtCore.QRect(200, 100, 41, 29))
        self.dw_38.setObjectName("dw_38")
        self.s1__lb_55 = QtWidgets.QLabel(self.groupBox)
        self.s1__lb_55.setGeometry(QtCore.QRect(10, 140, 108, 29))
        self.s1__lb_55.setObjectName("s1__lb_55")
        self.outTor = QtWidgets.QTextBrowser(self.groupBox)
        self.outTor.setGeometry(QtCore.QRect(90, 140, 101, 31))
        self.outTor.setObjectName("outTor")
        self.dw_39 = QtWidgets.QLabel(self.groupBox)
        self.dw_39.setGeometry(QtCore.QRect(200, 140, 41, 29))
        self.dw_39.setObjectName("dw_39")
        self.s1__lb_56 = QtWidgets.QLabel(self.groupBox)
        self.s1__lb_56.setGeometry(QtCore.QRect(10, 180, 108, 29))
        self.s1__lb_56.setObjectName("s1__lb_56")
        self.setPID = QtWidgets.QTextBrowser(self.groupBox)
        self.setPID.setGeometry(QtCore.QRect(90, 180, 101, 31))
        self.setPID.setObjectName("setPID")
        self.dw_40 = QtWidgets.QLabel(self.groupBox)
        self.dw_40.setGeometry(QtCore.QRect(200, 180, 41, 29))
        self.dw_40.setObjectName("dw_40")
        self.s1__lb_57 = QtWidgets.QLabel(self.groupBox)
        self.s1__lb_57.setGeometry(QtCore.QRect(10, 220, 108, 29))
        self.s1__lb_57.setObjectName("s1__lb_57")
        self.backPID = QtWidgets.QTextBrowser(self.groupBox)
        self.backPID.setGeometry(QtCore.QRect(90, 220, 111, 31))
        self.backPID.setObjectName("backPID")
        self.dw_41 = QtWidgets.QLabel(self.groupBox)
        self.dw_41.setGeometry(QtCore.QRect(210, 220, 41, 29))
        self.dw_41.setObjectName("dw_41")
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_9.setGeometry(QtCore.QRect(340, 390, 301, 291))
        self.groupBox_9.setObjectName("groupBox_9")
        self.dw_42 = QtWidgets.QLabel(self.groupBox_9)
        self.dw_42.setGeometry(QtCore.QRect(200, 110, 41, 29))
        self.dw_42.setObjectName("dw_42")
        self.xState = QtWidgets.QTextBrowser(self.groupBox_9)
        self.xState.setGeometry(QtCore.QRect(100, 30, 111, 31))
        self.xState.setObjectName("xState")
        self.dw_43 = QtWidgets.QLabel(self.groupBox_9)
        self.dw_43.setGeometry(QtCore.QRect(200, 150, 41, 29))
        self.dw_43.setObjectName("dw_43")
        self.AI_2 = QtWidgets.QTextBrowser(self.groupBox_9)
        self.AI_2.setGeometry(QtCore.QRect(90, 150, 101, 31))
        self.AI_2.setObjectName("AI_2")
        self.s1__lb_58 = QtWidgets.QLabel(self.groupBox_9)
        self.s1__lb_58.setGeometry(QtCore.QRect(10, 30, 108, 29))
        self.s1__lb_58.setObjectName("s1__lb_58")
        self.s1__lb_59 = QtWidgets.QLabel(self.groupBox_9)
        self.s1__lb_59.setGeometry(QtCore.QRect(10, 70, 108, 29))
        self.s1__lb_59.setObjectName("s1__lb_59")
        self.s1__lb_60 = QtWidgets.QLabel(self.groupBox_9)
        self.s1__lb_60.setGeometry(QtCore.QRect(10, 110, 108, 29))
        self.s1__lb_60.setObjectName("s1__lb_60")
        self.AI_1 = QtWidgets.QTextBrowser(self.groupBox_9)
        self.AI_1.setGeometry(QtCore.QRect(90, 110, 101, 31))
        self.AI_1.setObjectName("AI_1")
        self.s1__lb_61 = QtWidgets.QLabel(self.groupBox_9)
        self.s1__lb_61.setGeometry(QtCore.QRect(10, 150, 108, 29))
        self.s1__lb_61.setObjectName("s1__lb_61")
        self.yState = QtWidgets.QTextBrowser(self.groupBox_9)
        self.yState.setGeometry(QtCore.QRect(100, 70, 111, 31))
        self.yState.setObjectName("yState")
        self.s1__lb_62 = QtWidgets.QLabel(self.groupBox_9)
        self.s1__lb_62.setGeometry(QtCore.QRect(10, 190, 108, 29))
        self.s1__lb_62.setObjectName("s1__lb_62")
        self.AI_3 = QtWidgets.QTextBrowser(self.groupBox_9)
        self.AI_3.setGeometry(QtCore.QRect(90, 190, 101, 31))
        self.AI_3.setObjectName("AI_3")
        self.dw_44 = QtWidgets.QLabel(self.groupBox_9)
        self.dw_44.setGeometry(QtCore.QRect(200, 190, 41, 29))
        self.dw_44.setObjectName("dw_44")
        self.s1__lb_63 = QtWidgets.QLabel(self.groupBox_9)
        self.s1__lb_63.setGeometry(QtCore.QRect(10, 230, 121, 29))
        self.s1__lb_63.setObjectName("s1__lb_63")
        self.HDO = QtWidgets.QTextBrowser(self.groupBox_9)
        self.HDO.setGeometry(QtCore.QRect(130, 230, 111, 31))
        self.HDO.setObjectName("HDO")
        self.dw_45 = QtWidgets.QLabel(self.groupBox_9)
        self.dw_45.setGeometry(QtCore.QRect(250, 230, 41, 29))
        self.dw_45.setObjectName("dw_45")
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_10.setGeometry(QtCore.QRect(650, 20, 331, 191))
        self.groupBox_10.setObjectName("groupBox_10")
        self.s1__lb_64 = QtWidgets.QLabel(self.groupBox_10)
        self.s1__lb_64.setGeometry(QtCore.QRect(20, 20, 108, 29))
        self.s1__lb_64.setObjectName("s1__lb_64")
        self.counter1 = QtWidgets.QTextBrowser(self.groupBox_10)
        self.counter1.setGeometry(QtCore.QRect(130, 20, 141, 31))
        self.counter1.setObjectName("counter1")
        self.s1__lb_65 = QtWidgets.QLabel(self.groupBox_10)
        self.s1__lb_65.setGeometry(QtCore.QRect(20, 60, 111, 29))
        self.s1__lb_65.setObjectName("s1__lb_65")
        self.runTime = QtWidgets.QTextBrowser(self.groupBox_10)
        self.runTime.setGeometry(QtCore.QRect(130, 60, 141, 31))
        self.runTime.setObjectName("runTime")
        self.dw_46 = QtWidgets.QLabel(self.groupBox_10)
        self.dw_46.setGeometry(QtCore.QRect(280, 60, 41, 29))
        self.dw_46.setObjectName("dw_46")
        self.s1__lb_66 = QtWidgets.QLabel(self.groupBox_10)
        self.s1__lb_66.setGeometry(QtCore.QRect(20, 100, 131, 29))
        self.s1__lb_66.setObjectName("s1__lb_66")
        self.runTimeAll = QtWidgets.QTextBrowser(self.groupBox_10)
        self.runTimeAll.setGeometry(QtCore.QRect(150, 100, 121, 31))
        self.runTimeAll.setObjectName("runTimeAll")
        self.dw_47 = QtWidgets.QLabel(self.groupBox_10)
        self.dw_47.setGeometry(QtCore.QRect(280, 100, 41, 29))
        self.dw_47.setObjectName("dw_47")
        self.s1__lb_67 = QtWidgets.QLabel(self.groupBox_10)
        self.s1__lb_67.setGeometry(QtCore.QRect(20, 140, 111, 29))
        self.s1__lb_67.setObjectName("s1__lb_67")
        self.runTimeAll_1 = QtWidgets.QTextBrowser(self.groupBox_10)
        self.runTimeAll_1.setGeometry(QtCore.QRect(130, 140, 141, 31))
        self.runTimeAll_1.setObjectName("runTimeAll_1")
        self.dw_48 = QtWidgets.QLabel(self.groupBox_10)
        self.dw_48.setGeometry(QtCore.QRect(280, 140, 41, 29))
        self.dw_48.setObjectName("dw_48")
        self.groupBox_11 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_11.setGeometry(QtCore.QRect(650, 220, 331, 181))
        self.groupBox_11.setObjectName("groupBox_11")
        self.s1__lb_68 = QtWidgets.QLabel(self.groupBox_11)
        self.s1__lb_68.setGeometry(QtCore.QRect(20, 20, 108, 29))
        self.s1__lb_68.setObjectName("s1__lb_68")
        self.powerLevel = QtWidgets.QTextBrowser(self.groupBox_11)
        self.powerLevel.setGeometry(QtCore.QRect(130, 20, 141, 31))
        self.powerLevel.setObjectName("powerLevel")
        self.dw_49 = QtWidgets.QLabel(self.groupBox_11)
        self.dw_49.setGeometry(QtCore.QRect(280, 20, 41, 29))
        self.dw_49.setObjectName("dw_49")
        self.s1__lb_69 = QtWidgets.QLabel(self.groupBox_11)
        self.s1__lb_69.setGeometry(QtCore.QRect(20, 60, 108, 29))
        self.s1__lb_69.setObjectName("s1__lb_69")
        self.voltLevel = QtWidgets.QTextBrowser(self.groupBox_11)
        self.voltLevel.setGeometry(QtCore.QRect(130, 60, 141, 31))
        self.voltLevel.setObjectName("voltLevel")
        self.dw_50 = QtWidgets.QLabel(self.groupBox_11)
        self.dw_50.setGeometry(QtCore.QRect(280, 60, 41, 29))
        self.dw_50.setObjectName("dw_50")
        self.s1__lb_70 = QtWidgets.QLabel(self.groupBox_11)
        self.s1__lb_70.setGeometry(QtCore.QRect(20, 100, 108, 29))
        self.s1__lb_70.setObjectName("s1__lb_70")
        self.curLevel = QtWidgets.QTextBrowser(self.groupBox_11)
        self.curLevel.setGeometry(QtCore.QRect(130, 100, 141, 31))
        self.curLevel.setObjectName("curLevel")
        self.dw_51 = QtWidgets.QLabel(self.groupBox_11)
        self.dw_51.setGeometry(QtCore.QRect(280, 100, 41, 29))
        self.dw_51.setObjectName("dw_51")
        self.s1__lb_71 = QtWidgets.QLabel(self.groupBox_11)
        self.s1__lb_71.setGeometry(QtCore.QRect(20, 140, 108, 29))
        self.s1__lb_71.setObjectName("s1__lb_71")
        self.version = QtWidgets.QTextBrowser(self.groupBox_11)
        self.version.setGeometry(QtCore.QRect(130, 140, 141, 31))
        self.version.setObjectName("version")
        self.groupBox_12 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_12.setGeometry(QtCore.QRect(650, 410, 331, 341))
        self.groupBox_12.setObjectName("groupBox_12")
        self.s1__lb_72 = QtWidgets.QLabel(self.groupBox_12)
        self.s1__lb_72.setGeometry(QtCore.QRect(20, 20, 108, 29))
        self.s1__lb_72.setObjectName("s1__lb_72")
        self.dw_52 = QtWidgets.QLabel(self.groupBox_12)
        self.dw_52.setGeometry(QtCore.QRect(280, 20, 41, 29))
        self.dw_52.setObjectName("dw_52")
        self.excite = QtWidgets.QTextBrowser(self.groupBox_12)
        self.excite.setGeometry(QtCore.QRect(130, 20, 141, 31))
        self.excite.setObjectName("excite")
        self.s1__lb_73 = QtWidgets.QLabel(self.groupBox_12)
        self.s1__lb_73.setGeometry(QtCore.QRect(20, 60, 108, 29))
        self.s1__lb_73.setObjectName("s1__lb_73")
        self.PGback = QtWidgets.QTextBrowser(self.groupBox_12)
        self.PGback.setGeometry(QtCore.QRect(130, 60, 141, 31))
        self.PGback.setObjectName("PGback")
        self.dw_53 = QtWidgets.QLabel(self.groupBox_12)
        self.dw_53.setGeometry(QtCore.QRect(280, 60, 41, 29))
        self.dw_53.setObjectName("dw_53")
        self.s1__lb_74 = QtWidgets.QLabel(self.groupBox_12)
        self.s1__lb_74.setGeometry(QtCore.QRect(20, 100, 108, 29))
        self.s1__lb_74.setObjectName("s1__lb_74")
        self.motorTor = QtWidgets.QTextBrowser(self.groupBox_12)
        self.motorTor.setGeometry(QtCore.QRect(130, 100, 141, 31))
        self.motorTor.setObjectName("motorTor")
        self.dw_54 = QtWidgets.QLabel(self.groupBox_12)
        self.dw_54.setGeometry(QtCore.QRect(280, 100, 41, 29))
        self.dw_54.setObjectName("dw_54")
        self.s1__lb_75 = QtWidgets.QLabel(self.groupBox_12)
        self.s1__lb_75.setGeometry(QtCore.QRect(20, 140, 108, 29))
        self.s1__lb_75.setObjectName("s1__lb_75")
        self.setTension = QtWidgets.QTextBrowser(self.groupBox_12)
        self.setTension.setGeometry(QtCore.QRect(130, 140, 141, 31))
        self.setTension.setObjectName("setTension")
        self.dw_55 = QtWidgets.QLabel(self.groupBox_12)
        self.dw_55.setGeometry(QtCore.QRect(280, 140, 41, 29))
        self.dw_55.setObjectName("dw_55")
        self.s1__lb_76 = QtWidgets.QLabel(self.groupBox_12)
        self.s1__lb_76.setGeometry(QtCore.QRect(20, 180, 108, 29))
        self.s1__lb_76.setObjectName("s1__lb_76")
        self.rollNow = QtWidgets.QTextBrowser(self.groupBox_12)
        self.rollNow.setGeometry(QtCore.QRect(130, 180, 141, 31))
        self.rollNow.setObjectName("rollNow")
        self.dw_56 = QtWidgets.QLabel(self.groupBox_12)
        self.dw_56.setGeometry(QtCore.QRect(280, 180, 41, 29))
        self.dw_56.setObjectName("dw_56")
        self.s1__lb_77 = QtWidgets.QLabel(self.groupBox_12)
        self.s1__lb_77.setGeometry(QtCore.QRect(20, 220, 108, 29))
        self.s1__lb_77.setObjectName("s1__lb_77")
        self.spdNow = QtWidgets.QTextBrowser(self.groupBox_12)
        self.spdNow.setGeometry(QtCore.QRect(130, 220, 141, 31))
        self.spdNow.setObjectName("spdNow")
        self.dw_57 = QtWidgets.QLabel(self.groupBox_12)
        self.dw_57.setGeometry(QtCore.QRect(280, 220, 41, 29))
        self.dw_57.setObjectName("dw_57")
        self.s1__lb_78 = QtWidgets.QLabel(self.groupBox_12)
        self.s1__lb_78.setGeometry(QtCore.QRect(20, 260, 108, 29))
        self.s1__lb_78.setObjectName("s1__lb_78")
        self.firstRollTime = QtWidgets.QTextBrowser(self.groupBox_12)
        self.firstRollTime.setGeometry(QtCore.QRect(130, 260, 141, 31))
        self.firstRollTime.setObjectName("firstRollTime")
        self.dw_58 = QtWidgets.QLabel(self.groupBox_12)
        self.dw_58.setGeometry(QtCore.QRect(280, 260, 41, 29))
        self.dw_58.setObjectName("dw_58")
        self.s1__lb_79 = QtWidgets.QLabel(self.groupBox_12)
        self.s1__lb_79.setGeometry(QtCore.QRect(20, 300, 108, 29))
        self.s1__lb_79.setObjectName("s1__lb_79")
        self.rollInit = QtWidgets.QTextBrowser(self.groupBox_12)
        self.rollInit.setGeometry(QtCore.QRect(130, 300, 141, 31))
        self.rollInit.setObjectName("rollInit")
        self.dw_59 = QtWidgets.QLabel(self.groupBox_12)
        self.dw_59.setGeometry(QtCore.QRect(280, 300, 41, 29))
        self.dw_59.setObjectName("dw_59")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.formGroupBox.setTitle(_translate("Form", "串口设置"))
        self.s1__lb_1.setText(_translate("Form", "串口检测："))
        self.s1__box_1.setText(_translate("Form", "检测串口"))
        self.s1__lb_2.setText(_translate("Form", "串口选择："))
        self.s1__lb_3.setText(_translate("Form", "波特率："))
        self.s1__box_3.setItemText(0, _translate("Form", "9600"))
        self.s1__box_3.setItemText(1, _translate("Form", "115200"))
        self.s1__box_3.setItemText(2, _translate("Form", "2400"))
        self.s1__box_3.setItemText(3, _translate("Form", "4800"))
        self.s1__box_3.setItemText(4, _translate("Form", "14400"))
        self.s1__box_3.setItemText(5, _translate("Form", "19200"))
        self.s1__box_3.setItemText(6, _translate("Form", "38400"))
        self.s1__box_3.setItemText(7, _translate("Form", "57600"))
        self.s1__box_3.setItemText(8, _translate("Form", "76800"))
        self.s1__box_3.setItemText(9, _translate("Form", "12800"))
        self.s1__box_3.setItemText(10, _translate("Form", "230400"))
        self.s1__box_3.setItemText(11, _translate("Form", "460800"))
        self.s1__lb_4.setText(_translate("Form", "数据位："))
        self.s1__box_4.setItemText(0, _translate("Form", "8"))
        self.s1__box_4.setItemText(1, _translate("Form", "7"))
        self.s1__box_4.setItemText(2, _translate("Form", "6"))
        self.s1__box_4.setItemText(3, _translate("Form", "5"))
        self.s1__lb_5.setText(_translate("Form", "校验位："))
        self.s1__box_5.setItemText(0, _translate("Form", "N"))
        self.open_button.setText(_translate("Form", "打开串口"))
        self.close_button.setText(_translate("Form", "关闭串口"))
        self.s1__lb_6.setText(_translate("Form", "停止位："))
        self.s1__box_6.setItemText(0, _translate("Form", "1"))
        self.formGroupBox1.setTitle(_translate("Form", "串口状态"))
        self.label.setText(_translate("Form", "已接收："))
        self.label_2.setText(_translate("Form", "已发送："))
        self.groupBox_2.setTitle(_translate("Form", "参数设置"))
        self.s1__lb_22.setText(_translate("Form", "设备号："))
        self.Identity.setText(_translate("Form", "01"))
        self.s1__lb_23.setText(_translate("Form", "控制命令："))
        self.lineEdit_7.setText(_translate("Form", "0"))
        self.s1__lb_20.setText(_translate("Form", "频率设置："))
        self.lineEdit_6.setText(_translate("Form", "50"))
        self.dw_10.setText(_translate("Form", "Hz"))
        self.s1__lb_21.setText(_translate("Form", "给定频率上限："))
        self.lineEdit_4.setText(_translate("Form", "50"))
        self.dw_11.setText(_translate("Form", "Hz"))
        self.s1__lb_24.setText(_translate("Form", "PID给定值："))
        self.lineEdit_8.setText(_translate("Form", "0"))
        self.dw_12.setText(_translate("Form", "%"))
        self.s1__lb_25.setText(_translate("Form", "PID反馈值："))
        self.lineEdit_9.setText(_translate("Form", "0"))
        self.dw_13.setText(_translate("Form", "%"))
        self.s1__lb_26.setText(_translate("Form", "AO1输出值设置："))
        self.lineEdit_10.setText(_translate("Form", "0"))
        self.dw_14.setText(_translate("Form", "%"))
        self.s1__lb_27.setText(_translate("Form", "AO2输出值设置："))
        self.lineEdit_11.setText(_translate("Form", "0"))
        self.dw_15.setText(_translate("Form", "%"))
        self.s1__lb_28.setText(_translate("Form", "HDO输出值设置："))
        self.lineEdit_12.setText(_translate("Form", "0"))
        self.dw_16.setText(_translate("Form", "%"))
        self.s1__lb_29.setText(_translate("Form", "转矩设定值："))
        self.lineEdit_13.setText(_translate("Form", "0"))
        self.dw_17.setText(_translate("Form", "%"))
        self.s1__lb_30.setText(_translate("Form", "转矩控制正转最大频率："))
        self.lineEdit_14.setText(_translate("Form", "0"))
        self.dw_18.setText(_translate("Form", "Hz"))
        self.s1__lb_31.setText(_translate("Form", "转矩控制反转最大频率："))
        self.lineEdit_15.setText(_translate("Form", "0"))
        self.dw_19.setText(_translate("Form", "Hz"))
        self.s1__lb_32.setText(_translate("Form", "张力设定值："))
        self.lineEdit_16.setText(_translate("Form", "0"))
        self.dw_20.setText(_translate("Form", "N"))
        self.s1__lb_33.setText(_translate("Form", "卷径设定值："))
        self.lineEdit_17.setText(_translate("Form", "0"))
        self.dw_21.setText(_translate("Form", "MM"))
        self.s1__lb_34.setText(_translate("Form", "线速度设定值："))
        self.lineEdit_18.setText(_translate("Form", "0"))
        self.dw_22.setText(_translate("Form", "M/S"))
        self.s1__lb_35.setText(_translate("Form", "厚度设定值："))
        self.lineEdit_19.setText(_translate("Form", "0"))
        self.dw_23.setText(_translate("Form", "M"))
        self.groupBox_3.setTitle(_translate("Form", "操作指令"))
        self.s3__send_button_3.setText(_translate("Form", "获取电机信息"))
        self.send_SET.setText(_translate("Form", "参数配置设定"))
        self.polling.setText(_translate("Form", "轮询查询"))
        self.pollingtime.setText(_translate("Form", "10000"))
        self.dw_2.setText(_translate("Form", "ms/次"))
        self.groupBox_4.setTitle(_translate("Form", "运行信息"))
        self.groupBox_5.setTitle(_translate("Form", "故障及报警"))
        self.s1__lb_38.setText(_translate("Form", "变频器预报警信息："))
        self.s1__lb_36.setText(_translate("Form", "变频器运行状态："))
        self.faultType.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.runState.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.faultInfo.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.s1__lb_37.setText(_translate("Form", "变频器故障类型："))
        self.groupBox_6.setTitle(_translate("Form", "状态信息2"))
        self.min_volt.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.dw_25.setText(_translate("Form", "V"))
        self.s1__lb_42.setText(_translate("Form", "本次运行最高温度："))
        self.dw_24.setText(_translate("Form", "/10A"))
        self.motorspd_12.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.max_temper.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.s1__lb_43.setText(_translate("Form", "本次运行最低母线电压："))
        self.max_volt.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.max_cur.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.s1__lb_39.setText(_translate("Form", "变频器运行状态2："))
        self.s1__lb_40.setText(_translate("Form", "本次运行最大电流值："))
        self.dw_27.setText(_translate("Form", "V"))
        self.s1__lb_41.setText(_translate("Form", "本次运行最高母线电压："))
        self.dw_26.setText(_translate("Form", "℃"))
        self.outCur.setTitle(_translate("Form", "运行信息"))
        self.s1__lb_44.setText(_translate("Form", "给定频率："))
        self.setFreq.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.dw_28.setText(_translate("Form", "Hz"))
        self.s1__lb_45.setText(_translate("Form", "输出频率："))
        self.outFreq.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.dw_29.setText(_translate("Form", "Hz"))
        self.s1__lb_46.setText(_translate("Form", "输出电流："))
        self.outCur_2.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.dw_30.setText(_translate("Form", "A"))
        self.s1__lb_47.setText(_translate("Form", "输入电压："))
        self.inVolt.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.dw_31.setText(_translate("Form", "V"))
        self.s1__lb_48.setText(_translate("Form", "输出电压："))
        self.dw_32.setText(_translate("Form", "V"))
        self.outVolt.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.s1__lb_49.setText(_translate("Form", "机械速度："))
        self.motorspd_t.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.dw_33.setText(_translate("Form", "M/S"))
        self.s1__lb_50.setText(_translate("Form", "母线电压："))
        self.busVolt.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.dw_34.setText(_translate("Form", "V"))
        self.s1__lb_51.setText(_translate("Form", "输出功率："))
        self.outPower.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.dw_35.setText(_translate("Form", "KW"))
        self.groupBox.setTitle(_translate("Form", "运行信息2"))
        self.dw_36.setText(_translate("Form", "℃"))
        self.temper1.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.s1__lb_52.setText(_translate("Form", "模块温度1："))
        self.dw_37.setText(_translate("Form", "℃"))
        self.temper2.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.s1__lb_53.setText(_translate("Form", "模块温度2："))
        self.s1__lb_54.setText(_translate("Form", "设定转矩："))
        self.setTor.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.dw_38.setText(_translate("Form", "%"))
        self.s1__lb_55.setText(_translate("Form", "输出转矩："))
        self.outTor.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.dw_39.setText(_translate("Form", "%"))
        self.s1__lb_56.setText(_translate("Form", "PID给定量："))
        self.setPID.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.dw_40.setText(_translate("Form", "%"))
        self.s1__lb_57.setText(_translate("Form", "PID反馈量："))
        self.backPID.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.dw_41.setText(_translate("Form", "%"))
        self.groupBox_9.setTitle(_translate("Form", "运行信息3"))
        self.dw_42.setText(_translate("Form", "V"))
        self.xState.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.dw_43.setText(_translate("Form", "V"))
        self.AI_2.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.s1__lb_58.setText(_translate("Form", "输入端子X状态："))
        self.s1__lb_59.setText(_translate("Form", "输出端子Y状态："))
        self.s1__lb_60.setText(_translate("Form", "模拟量AI1："))
        self.AI_1.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.s1__lb_61.setText(_translate("Form", "模拟量AI2："))
        self.yState.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.s1__lb_62.setText(_translate("Form", "模拟量AI3："))
        self.AI_3.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.dw_44.setText(_translate("Form", "mA"))
        self.s1__lb_63.setText(_translate("Form", "脉冲信号HDO输出值："))
        self.HDO.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.dw_45.setText(_translate("Form", "kHz"))
        self.groupBox_10.setTitle(_translate("Form", "时间信息"))
        self.s1__lb_64.setText(_translate("Form", "计数器计数值："))
        self.counter1.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.s1__lb_65.setText(_translate("Form", "本次上电运行时间："))
        self.runTime.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.dw_46.setText(_translate("Form", "小时"))
        self.s1__lb_66.setText(_translate("Form", "本次上电累计运行时间："))
        self.runTimeAll.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.dw_47.setText(_translate("Form", "小时"))
        self.s1__lb_67.setText(_translate("Form", "本次累计运行时间："))
        self.runTimeAll_1.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.dw_48.setText(_translate("Form", "小时"))
        self.groupBox_11.setTitle(_translate("Form", "变频器信息"))
        self.s1__lb_68.setText(_translate("Form", "变频器功率等级："))
        self.powerLevel.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.dw_49.setText(_translate("Form", "KW"))
        self.s1__lb_69.setText(_translate("Form", "变频器额定电压："))
        self.voltLevel.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.dw_50.setText(_translate("Form", "V"))
        self.s1__lb_70.setText(_translate("Form", "变频器额定电流："))
        self.curLevel.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.dw_51.setText(_translate("Form", "A"))
        self.s1__lb_71.setText(_translate("Form", "软件版本："))
        self.version.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.groupBox_12.setTitle(_translate("Form", "负载相关"))
        self.s1__lb_72.setText(_translate("Form", "电机励磁分量："))
        self.dw_52.setText(_translate("Form", "A"))
        self.excite.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.s1__lb_73.setText(_translate("Form", "PG反馈频率："))
        self.PGback.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.dw_53.setText(_translate("Form", "Hz"))
        self.s1__lb_74.setText(_translate("Form", "电机额定转矩："))
        self.motorTor.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.dw_54.setText(_translate("Form", "NM"))
        self.s1__lb_75.setText(_translate("Form", "设定张力："))
        self.setTension.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.dw_55.setText(_translate("Form", "N"))
        self.s1__lb_76.setText(_translate("Form", "当前卷径："))
        self.rollNow.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.dw_56.setText(_translate("Form", "mm"))
        self.s1__lb_77.setText(_translate("Form", "当前线速度："))
        self.spdNow.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.dw_57.setText(_translate("Form", "m/s"))
        self.s1__lb_78.setText(_translate("Form", "当前一卷耗时："))
        self.firstRollTime.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.dw_58.setText(_translate("Form", "S"))
        self.s1__lb_79.setText(_translate("Form", "初始卷径："))
        self.rollInit.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.dw_59.setText(_translate("Form", "mm"))

